#!/bin/bash
# This script will start and stop your custom keyboard if you have installed sogoupinyin. 
# It belongs in the /usr/sbin folder.
# Creator: Frank Liu
# 
# COMMANDS:
# sudo custom-us --start      ->  starts up your custom keyboard and
# sudo custom-us --stop       ->  starts up your sogou pinyin keyboard 
#
# TO RUN WITH KEYBOARD SHORTCUTS USE:
# gksudo --bash custom-us --start
# gksudo --bash custom-us --stop
#
# The script does its job by: 
# Commenting lines out of startup scripts so the fcitx does not start when you want to use custom keyboard, and fcitx starts when you don't want to use your custom keyboard
#
# NOTE: If this script returns an error, you may have to change the command in the variable LOGOUT. The current command
# does not guarentee that you can log out of your computer.
# If required, you can also change it into "shutdown -now"
# 
LOGOUT=sudo systemctl restart lightdm

# Ensures root permissions
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

if [[ $@ == "--start" ]]; then
  # Prevents loadup of sogoupinyin and fcitx
  sudo sed -i 's/export XMODIFIERS=@im=fcitx/#export XMODIFIERS=@im=fcitx/' /etc/X11/Xsession.d/*sogoupinyin
  elif [[ $@ == "--stop" ]]; then 
  # Allows loadup of sogoupinyin and fcitx
  sudo sed -i 's/#export XMODIFIERS=@im=fcitx/export XMODIFIERS=@im=fcitx/' /etc/X11/Xsession.d/*sogoupinyin
fi

eval $LOGOUT


