#!/bin/bash 
# MAY not work perfectly if you have edited xkb files 
if ! [[ $PWD =~ /Compose$ ]]; then 
  read -p "Compose directory not found. Please cd into the Compose directory before excecuting this script. If you are sure you are in the right directory, press [ENTER] to continue. " 
  if ! [[ $key == "" ]]; then
    exit 0
  fi
fi
echo "Installing the custom-us keyboard"

ls -s $PWD/Compose ~/.XCompose
cat us | sudo tee -a /usr/share/X11/xkb/symbols/us

sudo ./.install.py

sudo cp /usr/share/X11/xkb/rules/evdev.lst /usr/share/X11/xkb/rules/base.lst
sudo cp /usr/share/X11/xkb/rules/evdev.xml /usr/share/X11/xkb/rules/base.xml

setxkbmap
echo "Please use the following command to finish unistallation (you will log out): sudo systemctl restart lightdm"
echo "Upon login, the custom-us keyboard should pop up as one of your system's available keyboards"
